### ISSUE TITLE
[Fix] 내일기뷰 제외 전체 디자인이슈 수정

### ISSUE THREAD

**Issue by jumining** [Team-Smeme/Smeme-iOS#168]
## Issue

내일기뷰 제외 전체 디자인이슈 수정(OpenDiary, Scrap)

## To-do

- [x] 그림자 적용 위한 계층 변경
- [x] 둘러보기 상세뷰 레이아웃 수정
- [x] 스크롤뷰 길이 수정
- [x] 로고수정
