### ISSUE TITLE
[Feat] 키보드 관련 notification 구현

### ISSUE THREAD

**Issue by cchanmi** [Team-Smeme/Smeme-iOS#18]
## Issue

- 키보드 관련 notification 구현

## To-do

- [ ] 키보드 활설화시 바텀뷰 위치
- [ ] SE의 경우 따로 분기 처리
- [ ] 화면 진입시 키보드 활성화
