### ISSUE TITLE
[Feat] DiaryForeign 뷰 하단 바 UI 구현

### ISSUE THREAD

**Issue by joonBaek12** [Team-Smeme/Smeme-iOS#19]
## Issue

Keyboard와 함께 올라갔다 내려갔다 하는 버튼을 구현합니다.
## To-do

- [ ] UIView 생성 2ea
- [ ] UIImageView, UILabel 생성
- [ ] UIView로 UIImageView, UILabel 감싸기
