### ISSUE TITLE
[Chore] - 오탈자 및 폴더명 수정

### ISSUE THREAD

**Issue by joonBaek12** [Team-Smeme/Smeme-iOS#203]
## Issue

폴더링 오탈자와 폴더명을 변경합니다.
## To-do

- [ ] ScrapOpen 폴더명 수정
- [ ] KoreanDiary 폴더명 수정
- [ ] ForeignDiary 폴더명 수정
