### ISSUE TITLE
[Feat] 로그인 분기처리

### ISSUE THREAD

**Issue by jumining** [Team-Smeme/Smeme-iOS#46]
## Issue

로그인 분기처리

## To-do

- [ ] 토큰이 있고 닉네임 있는 경우 -> 홈 (기존유저, 재로그인)
- [ ] 토큰이 있고 닉네임 없는 경우 -> 닉네임 입력 (회원가입)
- [ ] 토큰이 없는 경우 -> 소셜로그인
